[package]
name = "autodl"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.0-rc.2"
chrono = "0.4.23"
lazy_static = "1.4"
log = "0.4"
anyhow = "1.0"

[dependencies.rocket_dyn_templates]
version = "0.1.0-rc.2"
features = ["handlebars", "tera"]